### ISSUE TITLE
consider dropping hard requirement on Server::Starter

### ISSUE THREAD

**Issue by rjbs** [kazeburo/Gazelle#11]
This is very much like [a ticket I filed against Starlet](https://rt.cpan.org/Ticket/Display.html?id=106455).

I would like to use Gazelle. Our systems are Solaris. Server::Starter does not work on Solaris: 
http://matrix.cpantesters.org/?dist=Server-Starter+0.31

I could try to make it work, but it looks like Gazelle only uses it to pick a port number in limited circumstances. This could probably be made optional so that Server::Starter was not a hard requirement.

This would be a big improvement for "just working" on Solaris.

Thanks!

**Comment by syohex** [comment]
https://github.com/kazuho/p5-Server-Starter/pull/40

I sent PR to Server::Starter for Solaris and it was merged. I confirmed that its tests are passed on Solaris 11.1 i386 with that patch.

**Comment by rjbs** [comment]
Thank you for looking into this so I did not have to!  I appreciate your work and look forward to installing and testing this server.

**Comment by syohex** [comment]
Version 0.32 is released.
- https://metacpan.org/release/KAZUHO/Server-Starter-0.32

**Comment by rjbs** [comment]
Thank you.  I was able to install Server::Starter v0.32 on Solaris.  I did encounter one bit of difficulty, which I'm not sure about:  the requirement for Test::TCP 2.08 wasn't detected.  I had 2.06 installed, so the import of can_bind failed.  I'm not sure if this was because of my version of CPAN.pm or what.

Anyway, once it all installed, everything worked well and I installed Starlet.  Thanks again!
