### ISSUE TITLE
Doesn't support Unix Domain Sockets

### ISSUE THREAD

**Issue by frioux** [kazeburo/Gazelle#14]
`plackup --listen $HOME/test.sock -s Gazelle -a test.psgi` actually ends up listening on `0.0.0.0:8080`, instead of the socket.

**Comment by kazeburo** [comment]
You can listen unix domain socket with [start_server](https://metacpan.org/pod/distribution/Server-Starter/script/start_server)

e.g.
<pre>
$ start_server --path /path/to/app.sock -- plackup -s Gazelle  -a app.psgi
</ore>
