### ISSUE TITLE
Doesn't log on listen

### ISSUE THREAD

**Issue by frioux** [kazeburo/Gazelle#15]
Debugging #14 was very difficult because Gazelle does not log a "listen line" like many other Plack handlers.

Just to be clear

 * Starman says: `Starman: Accepting connections at http://*:5000/`
 * Starlet says: `Plack::Handler::Starlet: Accepting connections at http://0:5000/`
 * HTTP::Server::PSGI says: `HTTP::Server::PSGI: Accepting connections at http://0:5000/`

where Gazelle says nothing.

**Comment by kazeburo** [comment]
This issue will be fixed in next release. Thank you.

**Comment by kazeburo** [comment]
0.31 has just been released.

```
$ plackup -Ilib -s Gazelle -e 'sub{}'
Plack::Handler::Gazelle: Accepting connections at http://0:5000/
```
