### ISSUE TITLE
--reload cause nginx return 502

### ISSUE THREAD

**Issue by shcabin** [kazeburo/Gazelle#20]
When using the --reload function, the updated will cause nginx return 502 , only a short time .
can smooth reload it? like nginx

$ plackup -s Gazelle   -workers=10 --max-reqs-per-child 10000 --min-reqs-per-child 5000  -a http_app.psgi   -E production   --reload --port 5004
nginx.conf:
        location / {
            proxy_pass  http://127.0.0.1:5004/;
            proxy_connect_timeout   5;
            proxy_send_timeout      10;
            proxy_read_timeout      30;
        }

**Comment by shcabin** [comment]
only a short time return 502

**Comment by kazeburo** [comment]
Please use server-starter for hot-deployment.
