### ISSUE TITLE
version 0.44 not work after start_server --restart

### ISSUE THREAD

**Issue by zhanghjster** [kazeburo/Gazelle#27]
If use start_server run the server, the server will not reachable after restart. it seems the following code coz it.
       
>         #tell the socket we're done reading (stops new connections, existing will continue)
>         $self->{listen_sock}->shutdown(0);

**Comment by kazeburo** [comment]
Thank you reporting!

I fixed this.
https://github.com/kazeburo/Gazelle/commit/5d1af3261aa502fe7218e47fd3ba04ddfa084ffd

**Comment by kazeburo** [comment]
released  0.46
