### ISSUE TITLE
Keepalive?

### ISSUE THREAD

**Issue by kablamo** [kazeburo/Gazelle#6]
Thank you for writing Gazelle.  It looks very interesting.  Any plans to add keepalive?  Seems like most people would want that?

**Comment by davehodg** [comment]
In my experience, any application server which is expensive in resources, should be fronted by a reverse proxy and in that situation, keepalive is a Bad Idea. Many connection to the internet, many fewer to the app server.

**Comment by kablamo** [comment]
I don't quite follow you.  I thought it would be a good idea because Gazelle and nginx would reuse their existing connections?  So my theory is tying up starman procs on a long running connection is not a problem, because they will be reused.  What am I misunderstanding?

Thanks @davehodg !

**Comment by kazeburo** [comment]
In the high traffic environment, persistent connection between reverse proxy and reverse proxy causes app server's worker shortage. It's difficult to tune the nginx's keepalive directive.
If app server and reverse proxy runs on same host, I recommend to use unix domain socket. It is able to reduce TCP connection cost.

**Comment by kablamo** [comment]
Thanks for the clarification guys.

**Comment by davehodg** [comment]
...and if it doesn't cause a worker shortage, and if your code is memory-expensive (which perl tends to be), you keep forking (in Apache world), will run out of memory and enter a death spiral. Trust me, this is not desirable!

**Comment by vividsnow** [comment]
it would be nice to have keepalive in particular server-to-server environments
