### ISSUE TITLE
Documentation mentions --backlog option

### ISSUE THREAD

**Issue by robn** [kazeburo/Gazelle#8]
Documentation says:

```
$ start_server --path /path/to/app.sock --backlog 16384 -- plackup -s Gazelle \
  -workers=20 --max-reqs-per-child 1000 --min-reqs-per-child 800 -E production -a app.psgi
```

But --backlog isn't mentioned elsewhere, nor can I find it in the code. (Starlet does have this option, but its undocumented).

Do you want a doc patch for this?

**Comment by niner** [comment]
The --backlog and --path options in this example are start_server's options, not Gazelle's. Please see https://metacpan.org/pod/distribution/Server-Starter/script/start_server for more information.

I suggest closing this issue.

**Comment by robn** [comment]
Hmm, fair enough. I missed that bit and have never used start_server. No probs, thanks!
